let nome = "Jones Souza";
let idade = 24;
let biografia = "Desenvolvedor e Palmeirense, amo tecnologia, história, jogar xadrez e jogos no pc";
let amigos = [
    ["Pedro", "Amigo de jogos"],
    ["Natalia", "Colega de Trabalho"],
    ["Kailane", "Namorada <3"],
];

let localizacao = {
    país: "Brasil",
    estado: "São Paulo"
}

let interesses = ["Programação", "Livros", "Músicas"];
let statusConta = "Online";

console.log("Nome:", nome);
console.log("Idade:", idade);
console.log("Bio:", biografia);
console.log("Lista de amigos:", amigos);
console.log("Local:", localizacao);
console.log("Interesses:", interesses);
console.log("Status da conta:", statusConta);